# Simple genetic algorithm

## Step-by-step implementation

##### T V Bhaskarachary (丁陽)
##### Computer Science and Information Engineering * Tamkang University, Taiwan

In [ ]:
import numpy as np
#initiate random number generator
seed = 1
rnge = np.random.default_rng(seed)

# population number
population_size = 4

In [28]:
# initialize the population
population = list()
for i in range(population_size):
    gene = rnge.integers(low=0, high=2, size=5, dtype=np.uint8)
    population.append(gene)

population

[array([1, 0, 1, 0, 1], dtype=uint8),
 array([0, 0, 0, 1, 0], dtype=uint8),
 array([0, 0, 1, 0, 0], dtype=uint8),
 array([1, 0, 1, 0, 0], dtype=uint8)]

In [29]:
# generation decoding function
def gene_decode(gene):
    n = gene.shape[0]
    b = 2**np.arange(n)
    sum_x = np.sum(b * np.flip(gene))
    return sum_x

In [30]:
# decode the genotype
genotype_decode = [gene_decode(g) for g in population]

genotype_decode

[21, 2, 4, 20]

In [31]:
# calculate fitness for each individual
fitness = np.square(genotype_decode)

fitness

array([441,   4,  16, 400], dtype=int32)

In [32]:
# calculate the probability that an individual will be chosen to become a parent
parenting_probability = fitness/np.sum(fitness)

parenting_probability

array([0.51219512, 0.00464576, 0.01858304, 0.46457607])

In [33]:
# calculate the expected number of copies of each individual after selection
expected_count = fitness/np.mean(fitness)

expected_count

array([2.04878049, 0.01858304, 0.07433217, 1.8583043 ])

In [34]:
# calculate the actual number of copies in the mating pool
actual_count = np.around(expected_count, decimals=0).astype(int)
while sum(actual_count) < population_size:
    actual_count[np.argmax(expected_count)] += 1

actual_count

array([2, 0, 0, 2])

In [35]:
# form the mating pool
mating_pool = list()
for i, count in enumerate(actual_count):
    for j in range(count):
        mating_pool.append(population[i])

mating_pool

[array([1, 0, 1, 0, 1], dtype=uint8),
 array([1, 0, 1, 0, 1], dtype=uint8),
 array([1, 0, 1, 0, 0], dtype=uint8),
 array([1, 0, 1, 0, 0], dtype=uint8)]

In [36]:
# form pairs at random
arranged_mates = list(rnge.permutation(mating_pool))
formed_pairs = [(arranged_mates[i], arranged_mates[i+1]) for i in range(len(arranged_mates)) if i%2 == 0]

formed_pairs

[(array([1, 0, 1, 0, 1], dtype=uint8), array([1, 0, 1, 0, 1], dtype=uint8)),
 (array([1, 0, 1, 0, 0], dtype=uint8), array([1, 0, 1, 0, 0], dtype=uint8))]

In [38]:
# select the crossover point at random
children = list()
for pair in formed_pairs:
    xover = rnge.integers(1, 5)
    print(xover)
    child1 = np.concatenate((pair[0][:xover], pair[1][xover:]))
    child2 = np.concatenate((pair[1][:xover], pair[0][xover:]))
    children.append(child1)
    children.append(child2)

children

4
4


[array([1, 0, 1, 0, 1], dtype=uint8),
 array([1, 0, 1, 0, 1], dtype=uint8),
 array([1, 0, 1, 0, 0], dtype=uint8),
 array([1, 0, 1, 0, 0], dtype=uint8)]

In [39]:
# mutate the genes with mutation rate 0.001
mutation_rate  = 0.001
for child in children:
    for i, gene in enumerate(child):
        if rnge.uniform() < mutation_rate:
            print('Flipped in', child, i)
            if gene == 0:
                child[i] = 1
            else:
                child[i] = 0

children

[array([1, 0, 1, 0, 1], dtype=uint8),
 array([1, 0, 1, 0, 1], dtype=uint8),
 array([1, 0, 1, 0, 0], dtype=uint8),
 array([1, 0, 1, 0, 0], dtype=uint8)]

In [40]:
# replace the population with descendants
population = children

population

[array([1, 0, 1, 0, 1], dtype=uint8),
 array([1, 0, 1, 0, 1], dtype=uint8),
 array([1, 0, 1, 0, 0], dtype=uint8),
 array([1, 0, 1, 0, 0], dtype=uint8)]

## Putting it all together

In [41]:
import numpy as np

# initiate random number generator
seed = 1
rnge = np.random.default_rng(seed)

# population number
population_size = 4

overall_fitness = list()
maximum_fitness = list()

# initialize the population
population = list()
for i in range(population_size):
    gene = rng.integers(low=0, high=2, size=5, dtype=np.uint8)
    population.append(gene)

In [42]:
def sga(population):    
    # gene decoding function
    def gene_decode(gene):
        n = gene.shape[0]
        b = 2**np.arange(n)
        x = np.sum(b * np.flip(gene))
        return x

    # decode the genotype
    genotype_decode = [gene_decode(g) for g in population]

    # calculate fitness for each individual
    fitness = np.square(genotype_decode)

    # calculate the probability that an individual will be chosen to become a parent
    parenting_probability = fitness/np.sum(fitness)

    # calculate the expected number of copies of each individual after selection
    expected_count = fitness/np.mean(fitness)

    # calculate the actual number of copies in the mating pool
    actual_count = np.around(expected_count, decimals=0).astype(int)
    while sum(actual_count) < population_size:
        actual_count[np.argmax(expected_count)] += 1

    # form the mating pool
    mating_pool = list()
    for i, count in enumerate(actual_count):
        for j in range(count):
            mating_pool.append(population[i])

    # form pairs at random
    arranged_mates = list(rnge.permutation(mating_pool))
    formed_pairs = [(arranged_mates[i], arranged_mates[i+1]) for i in range(len(arranged_mates)) if i%2 == 0]

    # select the crossover point at random
    children = list()
    for pair in formed_pairs:
        xover = rnge.integers(1, 5)
        child1 = np.concatenate((pair[0][:xover], pair[1][xover:]))
        child2 = np.concatenate((pair[1][:xover], pair[0][xover:]))
        children.append(child1)
        children.append(child2)

    # mutate the genes with mutation rate 0.001
    mutation_rate  = 0.001
    for child in children:
        for i, gene in enumerate(child):
            if rng.uniform() < mutation_rate:
                if gene == 0:
                    child[i] = 1
                else:
                    child[i] = 0

    # replace the population with descendants
    population = children

    # decode the new genotype
    genotype_decode = [gene_decode(g) for g in population]

    # calculate fitness for each new individual
    fitness = np.square(genotype_decode)

    return (population, fitness)

In [43]:
for i in range(10):
    population, fitness = sga(population)
    overall_fitness.append(fitness.sum())
    maximum_fitness.append(fitness.max())

In [44]:
overall_fitness

[1234, 1234, 1234, 1234, 1230, 1230, 1230, 1230, 1230, 1230]

In [45]:
maximum_fitness

[361, 361, 361, 361, 361, 361, 361, 361, 361, 361]

In [46]:
population

[array([1, 0, 0, 0, 1], dtype=uint8),
 array([1, 0, 0, 1, 1], dtype=uint8),
 array([1, 0, 0, 1, 0], dtype=uint8),
 array([1, 0, 0, 0, 0], dtype=uint8)]